### ISSUE TITLE
Can't enable staking

### ISSUE THREAD

**Issue by fentas** [NixPlatform/Nix-GUI#117] opened 2018-11-11 20:01 UTC
# How to reproduce

- Open wallet
- Wait for sync
- Click on **Staking**
- Then on the toggle box besides **Staking: off**
- Enter password and **click** (pressing _enter_ seems not to work) on **OK**

# More information

Sometimes I see a flicker the toggle box is enabled but instantly returns to off.

- Operating system and version: Ubuntu 18.04 \
within an docker image https://github.com/fentas/crypto/blob/master/nix/wallet-beta/Dockerfile
- Client version: v1.0.0 / v2.1.0 (nixd - preinstalled)

**Comment by mattt21** [comment] 2018-11-11 20:02
Duplicate of #93. Has been fixed, will be available in the next release.

**Closed by mattt21** 2018-11-11 20:02 UTC
